//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSem3
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountDetail
    {
        public int DiscountDetailId { get; set; }
        public int FlightId { get; set; }
        public int TypeDiscountId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> modifyDate { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual TypeDiscount TypeDiscount { get; set; }
    }
}
