//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSem3
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuantitySeatClass
    {
        public int QuantitySeatClassId { get; set; }
        public int PlaneId { get; set; }
        public int Quantity { get; set; }
        public int SeatClassId { get; set; }
    
        public virtual Plane Plane { get; set; }
        public virtual SeatClass SeatClass { get; set; }
    }
}
